spring.application.name=sb-ecom
Server.port=9090
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=
project.image=images/


spring.servlet.multipart.enabled=true
spring.mvc.formcontent.filter.enabled=false

#Values for JWT TOKENS
spring.app.jwtSecret=TXlTZWNyZXRLZXkxMjMhIzkxMjczOA==cgcjcvghctzxexctccvufhjvgdrxcghvncfhxyrrzfcghvjhvkgufrsxrxfgctydcytc
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom



logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG


# MY SQL CONNECTION PROPERTIES

#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=jyoshna@0710
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# POSTGRE SQL CONNECTION DB

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=rakesh@0710

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
